### ISSUE TITLE
关于A2S插件开服时会覆盖原配置与脚本的问题

### ISSUE THREAD

**Issue by PUTTER6** [joyrhyme/L4D2-Plugins#2]
启动日志见附件，从3143行服务器预设配置全部加载完成后，插件才开始执行，并在后面启动过程进行初始化，把原有配置重新更改，包括脚本也被重置。并重新强制换图为c1m1,，加载另外一个脚本
[新建文本文档.txt](https://github.com/joyrhyme/L4D2-Plugins/files/14353654/default.txt)

**Comment by joyrhyme** [comment]
A2S插件不涉及任何地图转换功能, 只会在mapstart事件触发后会查找地图名称并显示到a2sinfo上面..
而且地图本地化的名称加载肯定要等服务器地图全初始化完才进行.所以启动完才执行是正常的..
脚本重置方面问题, 我在测试常见三方图没出现问题..如果脚本出现问题, 可能就是三方地图装的太多,某些地图用全局名的nut脚本导致相互覆盖..因为看日志能看到你装了很多地图,甚至官方都不广播多出的地图了..(例如有2个地图,都用了coop.nut, 这就要看谁最后加载覆盖谁了)

**Comment by joyrhyme** [comment]
关于强制换图, 你要排查你自身使用的插件有没有涉及相关的功能或冲突.
我只能确保a2s_edit不包含任何切换地图的功能.
