### ISSUE TITLE
A2S_Info_Edit

### ISSUE THREAD

**Issue by txuk1x** [joyrhyme/L4D2-Plugins#3]
https://github.com/joyrhyme/L4D2-Plugins/blob/268cd55d1beecb618e0f05dc029d1fee1bb016ea/A2S_Info_Edit/A2S_Info_Edit.sp#L403
大佬，这里使用最新版的l4d2_source_keyvalues.inc后要改成int type吧？

**Comment by joyrhyme** [comment]
感谢反馈, 已修正~
